# Generated by Django 4.2.15 on 2024-09-03 23:55

import custom_types.enums
from django.db import migrations, models
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('subject', enumfields.fields.EnumField(enum=custom_types.enums.Subject, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('video_link', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
    ]
