# Generated by Django 4.2.15 on 2024-09-07 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_parent_id'),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='educator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.educator'),
        ),
    ]
